mysite/helpApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('studytimetable', views.studyTimetable, name='study'),
    path('examtimetable', views.examTimetable, name='exam'),
    path('checksubject', views.checkSubject, name='check'),
    path('settingtimetable', views.settingtable, name='table'),
    path('add_subject', views.add_subject_request, name='add_subject'),
    path('students_planning_to_register', views.students_planning_to_register, name='students_planning_to_register'),
    path('number_of_students_registered', views.number_of_students_registered, name='number_of_students_registered'),
    path('verify/<int:subject_ID>', views.verify, name='verify'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('generalApp.urls')),
    path('help/', include('helpApp.urls')),
    path('users/', include('userApp.urls')),
    path('admin/', admin.site.urls),
]

mysite/helpApp/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Subject(models.Model):
    subject_ID = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    mid_term = models.CharField(max_length=200, null=True,blank=True)
    final = models.CharField(max_length=200, null=True,blank=True)
    mid_term_date = models.CharField(max_length=200, null=True,blank=True)
    mid_term_start_time = models.CharField(max_length=200, null=True,blank=True)
    mid_term_end_time = models.CharField(max_length=200, null=True,blank=True)
    final_term_date = models.CharField(max_length=200, null=True,blank=True)
    final_term_start_time = models.CharField(max_length=200, null=True,blank=True)
    final_term_end_time = models.CharField(max_length=200, null=True,blank=True)
    def __str__(self):
        return self.name

class Section(models.Model):
    subject_ID = models.ForeignKey(Subject, on_delete=models.CASCADE)
    sec_num = models.CharField(max_length=200)
    day = models.CharField(max_length=200)
    time = models.CharField(max_length=200)
    teacher = models.CharField(max_length=200)
    start_time = models.CharField(max_length=200, null=True,blank=True)
    end_time = models.CharField(max_length=200, null=True,blank=True)

    def __str__(self):
        return f"{self.subject_ID.name} - Section {self.sec_num}"
    
    def duration(self):
        start = datetime.strptime(self.start_time, '%H:%M')
        end = datetime.strptime(self.end_time, '%H:%M')
        duration = (end - start).total_seconds() / 3600  # duration in hours
        return duration

mysite/helpApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Section, Subject
from userApp.models import User_subject
from django.db.models import Q,F
from django.http import JsonResponse
from django.contrib.auth.models import User
from .user_subject_manage import subject_manage
from .check_overlap import Overlap
from django.shortcuts import redirect

def studyTimetable(request):
    if request.user.is_authenticated:
        courses = User_subject.objects.filter(user_id=request.user)

        time_used = {'M': [], 'T': [], 'W': [], 'H': [], 'F': [], 'S': []}
        times = ['8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00']
        for course in courses:
            day = course.section.day
            start_t = course.section.start_time
            end_t = course.section.end_time
            keep = False
            for time in times:
                if start_t == time:
                    keep = True
                if end_t == time:
                    keep = False
                if (keep): 
                    time_used[day].append(time)
                
        return render(request, 'helpApp/studytimetable.html', {'course':courses, 'time':times, 'time_usedd':time_used})
    else:
        return render(request, 'helpApp/studytimetable.html')

def examTimetable(request):
    if request.user.is_authenticated:
        course_mid = User_subject.objects.filter(user_id=request.user).order_by(F('section__subject_ID__mid_term_date').asc(nulls_last=True))
        course_fin = User_subject.objects.filter(user_id=request.user).order_by(F('section__subject_ID__final_term_date').asc(nulls_last=True))
        return render(request, 'helpApp/examtimetable.html', {'course_m': course_mid, 'course_f': course_fin})
    else:
        return render(request, 'helpApp/examtimetable.html')

def checkSubject(request):
    if 'search-subject' in request.GET:
        q = request.GET.get('search-subject')
        #subject = Subject.objects.filter(subject_ID__icontains=q)
        multi_q = Q(Q(subject_ID__icontains=q) | Q(name__icontains=q))
        subject = Subject.objects.filter(multi_q)
    else:
        subject = Subject.objects.all()
    context = {'subject':subject}
    return render(request, 'helpApp/checksubject.html', context)

def settingtable(request):
    courses = User_subject.objects.filter(user_id=request.user)
    q = request.GET.get('search-subject', '')
    if q:
        multi_q = Q(Q(subject_ID__icontains=q) | Q(name__icontains=q))
        subject = Subject.objects.filter(multi_q).exclude(section__in=courses.values_list('section', flat=True))
    else:
        subject = Subject.objects.exclude(section__in=courses.values_list('section', flat=True))
    context = {
        'subject': subject,
        'course': courses,
        'qs': q,
    }
    return render(request, 'helpApp/settingtable.html', context)
def verify(request, subject_ID):
    subject = Subject.objects.get(id=subject_ID)
    return render(request, 'helpApp/checking.html',{'subject':subject})

def add_subject_request(request):
    if request.user.is_authenticated:
        user_name = request.user.username  
        user_pk = request.user.pk  # user_pk is an integer
        subject = Subject.objects.all()
        if request.method == 'POST':
            subject_id = request.POST.get('subject_id')
            sec_num = request.POST.get('section')

            m = subject_manage()
            if "add_btn" in request.POST:
                if m.can_submit(user_name, subject_id, sec_num):
                    print("Add", user_name, subject_id, sec_num)
                    m.add_subject(user_name, subject_id, sec_num)
                return redirect(settingtable)
                    
            if "del_btn" in request.POST:
                print("Delete", user_name, subject_id, sec_num)
                m.remove_subject(user_name, subject_id, sec_num)
                return redirect(studyTimetable)

            # return JsonResponse({'success': True}, status=400)
            # return render(request, 'helpApp/settingtable.html', {'subject':subject})
            

        else:
            subject = Subject.objects.all()
            return redirect(settingtable)
        

def students_planning_to_register(request):
    # Search subject
    if 'search-subject' in request.GET:
        q = request.GET.get('search-subject')
        #subject = Subject.objects.filter(subject_ID__icontains=q)
        multi_q = Q(Q(subject_ID__icontains=q) | Q(name__icontains=q))
        subject = Subject.objects.filter(multi_q)
    else:
        subject = Subject.objects.all()


    subject_list = {}
    # Decalre subject_list
    for sub in subject:
        subject_list[sub.subject_ID] = []

    
    # add student on each subject
    user_subject = User_subject.objects.all()
    for sub in subject:
        for user_sub in user_subject:
            # If user add section in that subject and that user have not add that subject (for subject 2 study day case)
            if sub.subject_ID == user_sub.section.subject_ID.subject_ID and user_sub.user_id.username not in subject_list[sub.subject_ID]:
                subject_list[sub.subject_ID].append(user_sub.user_id.username)

    # remove subject what have no student 
    list_for_remove = []
    for key in subject_list:
        if len(subject_list[key]) == 0:
            list_for_remove.append(key)
    for sub_ID in list_for_remove:
        del subject_list[sub_ID]      

    
    
    # sent to cilent
    context = {'subject':subject,  'subject_list':subject_list}
    return render(request, 'helpApp/students_planning_to_register.html', context)

def number_of_students_registered(request):
    # Search subject
    if 'search-subject' in request.GET:
        q = request.GET.get('search-subject')
        #subject = Subject.objects.filter(subject_ID__icontains=q)
        multi_q = Q(Q(subject_ID__icontains=q) | Q(name__icontains=q))
        subject = Subject.objects.filter(multi_q)
    else:
        subject = Subject.objects.all()

    subject_list = {}
    # Decalre 0 on subject_list
    for sub in subject:
        subject_list[sub.subject_ID] = []

    
    # add student on each subject
    user_subject = User_subject.objects.all()
    for sub in subject:
        for user_sub in user_subject:
            # If user add section in that subject and that user have not add that subject (for subject 2 study day case)
            if sub.subject_ID == user_sub.section.subject_ID.subject_ID and user_sub.user_id.username not in subject_list[sub.subject_ID]:
                subject_list[sub.subject_ID].append(user_sub.user_id.username)


    # remove subject what have no student 
    list_for_remove = []
    for key in subject_list:
        if len(subject_list[key]) == 0:
            # add to list for remove if have no student
            list_for_remove.append(key)
        else:
            # count user each subject
            subject_list[key] = len(subject_list[key])
    for sub_ID in list_for_remove:
        del subject_list[sub_ID]      
    
    # sent to cilent
    context = {'subject':subject, 'subject_list':subject_list}
    return render(request, 'helpApp/number_of_students_registered.html', context)

mysite/helpApp/templates/helpApp/checking.html
{% extends 'generalApp/components/base.html' %}

{% block title %} {{ subject.name }} | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>คุณสามารถลงเรียนวิชา {{ subject.name }} ได้หรือไม่</h1>
</div>



{% endblock %}

mysite/helpApp/templates/helpApp/checksubject.html
{% extends 'generalApp/components/base.html' %}

{% block title %}เช็ควิชาที่ลงได้ | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>เช็ควิชาที่ลงได้</h1>
</div>

<div class="content-section">
    <div class="content-container">
        <form method="get">
        <input type="search" name='search-subject' placeholder="Search">
        <button type="submit">Search</button>
        </form>
    
        <br>

        {% for subject in subject %}
        <div class="cardd">
            <div class="container-about">
                <br>
                <a class="button-link" href="{% url 'verify' subject.id %}">{{ subject.subject_ID}} {{ subject.name }}</a>
                <br>
                <br>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>
</div>

{% endblock %}

mysite/helpApp/templates/helpApp/examtimetable.html
{% extends 'generalApp/components/base.html' %}

{% block title %}ตารางสอบ | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>Exam Timetable</h1>
</div>

{% if user.is_authenticated %}
    <section class="content-section">
        <div class="content-container">
            <h2 class="content-title text-center">Mid-term</h2>
            {% regroup course_m by section.subject_ID as courses_by_mid %}
            {% for course in courses_by_mid %}
            <div class="card-about">
                <div class="container-about">
                    <br>
                    <h4>{{ course.grouper }} </h4>
                    <p>{{ course.grouper.midterm }}</p>
                </div>
            </div>
            <br>     
            {% endfor%}
        </div>
    </section>

    <section class="content-section">
        <div class="content-container">
            <h2 class="content-title text-center">Final</h2>
            {% regroup course_f by section.subject_ID as courses_by_fin %}
            {% for course in courses_by_fin %}
            <div class="card-about">
                <div class="container-about">
                    <br>
                    <h4>{{ course.grouper }} </h4>
                    <p>{{ course.grouper.final }}</p>
                </div>
            </div>
            <br>         
            {% endfor%}      
        </div>
    </section>
{% else %}



{% endif %}

{% endblock %}

mysite/helpApp/templates/helpApp/number_of_students_registered.html
{% extends 'generalApp/components/base.html' %}

{% block title %}จำนวนนักศึกษาที่ลงทะเบียนวิชาเรียน | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>จำนวนนักศึกษาที่ลงทะเบียนวิชาเรียน</h1>
</div>

<div class="content-section">
    <div class="content-container">
        <form method="get">
            <input type="search" name='search-subject' placeholder="Search">
            <button type="submit">Search</button>
            </form>
    
        <br>
        {% for subject in subject %}
        {% if subject.subject_ID in subject_list %}
            <div class="cardd">
                <div class="container-about">

                <a class="button-link" >{{ subject.subject_ID}} {{ subject.name }}</a>
                
                {% for subject_ID, value in subject_list.items  %}
                        {% if subject.subject_ID  == subject_ID %}
                            <h6>{{ value}} คน</h6> 
                        {% endif %}
                    {% endfor %}  

                </div>
            </div>

        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

mysite/helpApp/templates/helpApp/settingtable.html
{% extends 'generalApp/components/base.html' %}

{% block title %}ตั้งค่าตารางเรียน | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>Edit Study Timetable</h1>
</div>

<div class="content-section">
    <div class="content-container">
        <form method="get">
            <input type="search" size="65" name='search-subject' value="{{ qs }}" placeholder="Search">
            <button type="submit">Search</button>
            <br>
        </form>
    
        <br>

        {% for subject in subject %}
        <div class="cardd">
            <div class="container-about">
                <br>
                <a class="button-link" >{{ subject.subject_ID}} {{ subject.name }}</a>
                <br>
                <br>
                
                <form id="add-subject-form" action="{% url 'add_subject' %}" target="dummyframe" method="POST" >
                    <select name="section">
                        {% for section in subject.section_set.all %}
                        <option value="{{ section.sec_num }}">{{ section.sec_num }} {{ section.day }} {{ section.time }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <br>    
                        {% csrf_token %}
                        <input type="hidden" name="subject_id" value="{{ subject.subject_ID }}">
                        <button type="submit" class="button" name="add_btn">Add</button>
                </form>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>
</div>

{% endblock %}

mysite/helpApp/templates/helpApp/students_planning_to_register.html
{% extends 'generalApp/components/base.html' %}

{% block title %}รายชื่อนักศึกษาที่วางแผนจะลงทะเบียนวิชาเรียน | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>รายชื่อนักศึกษาที่วางแผนจะลงทะเบียนวิชาเรียน</h1>
</div>

<div class="content-section">
    <div class="content-container">
        <form method="get">
        <input type="search" name='search-subject' placeholder="Search">
        <button type="submit">Search</button>
        </form>
    
        <br>
        {% for subject in subject %}
            <div class="cardd">
                <div class="container-about">
                    
                    
                    <a class="button-link" >{{ subject.subject_ID}} {{ subject.name }}</a>
                    {% for sub_ID, users in subject_list.items%}
                        {% if sub_ID  == subject.subject_ID %}
                            {% for user in users %}
                            <br>{{ user }}
                            {% endfor %}   
                        {% endif %}
                    {% endfor %}    
                    <br>
                    <br>
                    
                </div>
            </div>
            <br>
           
        {% endfor %}
    </div>
</div>

{% endblock %}

mysite/helpApp/templates/helpApp/studytimetable.html
{% extends 'generalApp/components/base.html' %}


{% block title %}ตารางเรียน | {% endblock %}

{% block content %}

<div class="header-section">
    <h1>Study Timetable</h1>
</div>

<div class="content-section">
    <div class="content-container">
        
        <table>
            <tr>
                <td class="text-table">Day/Period</td>
                <td class="text-table">8:00</td>
                <td class="text-table">9:00</td>
                <td class="text-table">10:00</td>
                <td class="text-table">11:00</td>
                <td class="text-table">12:00</td>
                <td class="text-table">13:00</td>
                <td class="text-table">14:00</td>
                <td class="text-table">15:00</td>
                <td class="text-table">16:00</td>
                <td class="text-table">17:00</td>
                <td class="text-table">18:00</td>
                <td class="text-table">19:00</td>
                <td class="text-table">20:00</td>
            </tr>

            {% if user.is_authenticated %}
            <tr>
                <td class="text-table">Monday</td>
                {% for time in time %}
                    {% for course in course %}
                        {% if course.section.day == 'M' and course.section.start_time == time %}
                            <td style="font-size: 12px; background-color: beige;" colspan="{{ course.section.duration }}" >
                                {{ course.section.subject_ID.name }}<br>
                                {{ course.section.teacher }}<br>
                            </td>
                        {% elif time not in time_usedd.M and forloop.last %}
                            <td></td>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>

            <tr>
                <td class="text-table">Tuesday</td>
                {% for time in time %}
                    {% for course in course %}
                        {% if course.section.day == 'T' and course.section.start_time == time %}
                            <td style="font-size: 12px; background-color: beige;" colspan="{{ course.section.duration }}" >
                                {{ course.section.subject_ID.name }}<br>
                                {{ course.section.teacher }}<br>
                            </td>
                        {% elif time not in time_usedd.T and forloop.last %}
                            <td></td>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>

            <tr>
                <td class="text-table">Wednesday</td>
                {% for time in time %}
                    {% for course in course %}
                        {% if course.section.day == 'W' and course.section.start_time == time %}
                            <td style="font-size: 12px; background-color: beige;" colspan="{{ course.section.duration }}" >
                                {{ course.section.subject_ID.name }}<br>
                                {{ course.section.teacher }}<br>
                            </td>
                        {% elif time not in time_usedd.W and forloop.last %}
                            <td></td> 
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>

            <tr>
                <td class="text-table">Thursday</td>
                {% for time in time %}
                    {% for course in course %}
                        {% if course.section.day == 'H' and course.section.start_time == time %}
                            <td style="font-size: 12px; background-color: beige;" colspan="{{ course.section.duration }}" >
                                {{ course.section.subject_ID.name }}<br>
                                {{ course.section.teacher }}<br>
                            </td>
                        {% elif time not in time_usedd.H and forloop.last %}
                            <td></td>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>

            <tr>
                <td class="text-table">Friday</td>
                {% for time in time %}
                    {% for course in course %}
                        {% if course.section.day == 'F' and course.section.start_time == time %}
                            <td style="font-size: 12px; background-color: beige;" colspan="{{ course.section.duration }}" >
                                {{ course.section.subject_ID.name }}<br>
                                {{ course.section.teacher }}<br>
                            </td>
                        {% elif time not in time_usedd.F and forloop.last %}
                            <td></td>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>

            <tr>
                <td class="text-table">Saturday</td>
                {% for time in time %}
                    {% for course in course %}
                        {% if course.section.day == 'S' and course.section.start_time == time %}
                            <td style="font-size: 12px; background-color: beige;" colspan="{{ course.section.duration }}" >
                                {{ course.section.subject_ID.name }}<br>
                                {{ course.section.teacher }}<br>
                            </td>
                        {% elif time not in time_usedd.S and forloop.last %}
                            <td></td>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>

        </table>

        <br>

        <a class="button" href="{% url 'table' %}" style="float: right;">Edit Timetable</a>

        <br>
        <br>
        <br>

        {% regroup course by section.subject_ID as courses_by_subject %}

        {% for course_group in courses_by_subject %}
        <form id="add-subject-form" action="{% url 'add_subject' %}" target="dummyframe" method="POST" >
            <div class="cardd">
                <div class="container-about">
                <br>
                <a class="button-link">{{ course_group.grouper.subject_ID }} {{ course_group.grouper.name }}</a>
                <br>
                <br>   
                {% csrf_token %}
                <input type="hidden" name="subject_id" value="{{ course_group.grouper.subject_ID }}">
                <button type="submit" class="button-delete" name="del_btn">Delete</button>
                </div>
            </div>
        </form>
        {% endfor %}
        
        {% else %}
        <tr>
            <td class="text-table">Monday</td>
        </tr>

        <tr>
            <td class="text-table">Tuesday</td>
        </tr>

        <tr>
            <td class="text-table">Wednesday</td>
        </tr>

        <tr>
            <td class="text-table">Thursday</td>
        </tr>

        <tr>
            <td class="text-table">Friday</td>
        </tr>

        <tr>
            <td class="text-table">Saturday</td>
        </tr>
        {% endif %}

    </table>

        
    </div>

</div>


{% endblock %}